### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by shikha89** [officialarijit/DW-FedAvg#6]
open  **decay** is deprecated in the new Keras optimizer as tf.keras.optimizers.legacy.SGD. Error in this code

**Comment by officialarijit** [comment]
Hi! I'm sorry for not getting back to you sooner. 

**This is a regression that has happened in the TF 2.11 Release.** 
The issue disappears if you change to TF 2.10 (**!pip install tensorflow~=2.10.0**).

Switching to the legacy optimizer for the layer optimizer fixes the issue.

Please check the repo for the **requirements.txt** file for creating your Anadondaconda/python virtual environment creation.
  
The code is ok! Tested and updated.
